env:
  # GitHub Config
  GITHUB_USER: manusia
  GITHUB_EMAIL: ndktau@gmail.com
  
  # Device Config
  DEVICE_TREE: https://github.com/manusia251/twrp-test.git
  DEVICE_BRANCH: main
  DEVICE_CODENAME: X6512
  MANIFEST_BRANCH: fox_12.1
  TARGET_RECOVERY_IMAGE: boot
  
  # Build Environment
  ALLOW_MISSING_DEPENDENCIES: true
  FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER: 1
  LC_ALL: "C"
  USE_CCACHE: 1
  CCACHE_DIR: "/tmp/ccache"

task:
  name: "OrangeFox Recovery Build - Infinix X6512"
  timeout_in: 120m
  
  container:
    image: ubuntu:20.04
    cpu: 8
    memory: 32G
    
  setup_script:
    - |
      set -e
      echo "=== Setting up build environment ==="
      apt-get update -qq
      DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg \
        gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool \
        libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
        lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
        python3 python3-pip python-is-python3 repo wget ca-certificates \
        adb fastboot openssh-client openjdk-11-jdk lsb-release
      
      # Setup Java
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
      
  build_script:
    - |
      set -x
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      export USE_CCACHE=1
      export CCACHE_DIR="/tmp/ccache"
      export ALLOW_MISSING_DEPENDENCIES=true
      export USE_SSH=0
      ccache -M 20G || true
      
      echo "[DEBUG] Current directory: $(pwd)"
      echo "[DEBUG] Current directory files:" && ls -la
      
      if [ -f build_orangefox.sh ]; then 
        chmod +x build_orangefox.sh
        echo "[DEBUG] build_orangefox.sh found and made executable"
      else 
        echo "[ERROR] build_orangefox.sh not found!"
        echo "[DEBUG] Available files:"
        ls -la
        exit 1
      fi
      
      echo "[DEBUG] Environment variables:"
      echo "DEVICE_TREE: $DEVICE_TREE"
      echo "DEVICE_BRANCH: $DEVICE_BRANCH"
      echo "DEVICE_CODENAME: $DEVICE_CODENAME"
      echo "MANIFEST_BRANCH: $MANIFEST_BRANCH"
      echo "TARGET_RECOVERY_IMAGE: $TARGET_RECOVERY_IMAGE"
      
      echo "[DEBUG] Starting OrangeFox build..."
      bash -x ./build_orangefox.sh "$DEVICE_TREE" "$DEVICE_BRANCH" "$DEVICE_CODENAME" "$MANIFEST_BRANCH" "$TARGET_RECOVERY_IMAGE"
