container:
  image: ubuntu:20.04
  cpu: 8
  memory: 32G

env:
  DEVICE: Infinix-X6512

task:
  name: TWRP Build
  timeout_in: 120m
  
  setup_script: |
    apt-get update
    apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python python3 wget unzip openjdk-8-jdk
    mkdir -p ~/bin
    curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    chmod a+x ~/bin/repo
  
  sync_script: |
    cd ~
    mkdir twrp && cd twrp
    ~/bin/repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
    ~/bin/repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
  
  device_script: |
    cd ~/twrp
    git clone https://github.com/manusia251/twrp-test -b main device/infinix/Infinix-X6512
  
  build_script: |
    cd ~/twrp
    export ALLOW_MISSING_DEPENDENCIES=true
    source build/envsetup.sh
    lunch omni_Infinix-X6512-eng
    make recoveryimage -j$(nproc)
  
  check_script: |
    ls -la ~/twrp/out/target/product/Infinix-X6512/
