env:
  # GitHub Config
  GITHUB_USER: manusia
  GITHUB_EMAIL: ndktau@gmail.com
  
  # Device Config
  DEVICE_TREE: https://github.com/manusia251/twrp-test.git
  DEVICE_BRANCH: main
  DEVICE_CODENAME: X6512
  MANIFEST_BRANCH: twrp-12
  TARGET_RECOVERY_IMAGE: boot  # Changed from vendor_boot to boot
  
  # Build Environment
  ALLOW_MISSING_DEPENDENCIES: true
  LC_ALL: "C"
  USE_CCACHE: 1
  CCACHE_DIR: "/tmp/ccache"

task:
  name: "TWRP Boot Build - Infinix X6512"
  timeout_in: 120m
  
  container:
    image: ubuntu:20.04
    cpu: 8
    memory: 32G
    
  setup_script:
    - |
      set -e
      echo "=== Setting up build environment ==="
      
      # Update package list
      apt-get update -qq
      
      # Install required packages
      DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg \
        gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool \
        libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
        lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
        python3 python3-pip python-is-python3 wget ca-certificates \
        adb fastboot openssh-client openjdk-11-jdk lsb-release \
        software-properties-common
      
      # Setup Java
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      
      echo "=== Environment setup completed ==="
      
  build_script:
    - |
      set -x
      
      # Export environment variables
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      export USE_CCACHE=1
      export CCACHE_DIR="/tmp/ccache"
      export ALLOW_MISSING_DEPENDENCIES=true
      
      # Setup ccache
      ccache -M 20G || true
      
      # Make build script executable
      chmod +x build_twrp.sh
      
      # Start build with debug
      bash -x ./build_twrp.sh "$DEVICE_TREE" "$DEVICE_BRANCH" "$DEVICE_CODENAME" "$MANIFEST_BRANCH" "$TARGET_RECOVERY_IMAGE"

  always:
    artifacts:
      path: /tmp/cirrus-ci-build/output/*
      name: TWRP_Boot_Build
