task:
  name: Build OrangeFox X6512 (boot.img)
  container:
    image: ubuntu:20.04
    cpu: 8
    memory: 32G
  environment:
    DEVICE_TREE: https://github.com/manusia251/twrp-test.git
    DEVICE_BRANCH: main
    DEVICE_CODENAME: X6512
    MANIFEST_BRANCH: fox_11.0   # diabaikan oleh script (legacy)
    TARGET_RECOVERY_IMAGE: boot
    DEBIAN_FRONTEND: noninteractive
  install_script:
    - apt-get update
    - apt-get install -y --no-install-recommends \
        ca-certificates git curl wget unzip zip rsync bc build-essential \
        gcc g++ make pkg-config flex bison gperf \
        libssl-dev libxml2-utils xsltproc zlib1g-dev libncurses5 libncurses5-dev libtinfo5 \
        libx11-dev libgl1-mesa-dev fontconfig \
        python3 python-is-python3 \
        openjdk-11-jdk \
        ccache lz4 zstd
    - curl -s https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
    - chmod +x /usr/local/bin/repo
    - git config --global user.name "mana251"
    - git config --global user.email "darke@gmail.com"
    - git config --global color.ui false
  script:
    - set -x
    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    - export PATH=$JAVA_HOME/bin:$PATH
    - export USE_CCACHE=1
    - export CCACHE_DIR="/tmp/ccache"
    - ccache -M 20G || true
    - echo "Current directory files:" && ls -la
    - if [ -f build_twrp.sh ]; then chmod +x build_twrp.sh; else echo "build_twrp.sh not found!"; ls -la; exit 1; fi
    - echo "DEVICE_TREE: $DEVICE_TREE"
    - echo "DEVICE_BRANCH: $DEVICE_BRANCH"
    - echo "DEVICE_CODENAME: $DEVICE_CODENAME"
    - echo "MANIFEST_BRANCH: $MANIFEST_BRANCH"
    - echo "TARGET_RECOVERY_IMAGE: $TARGET_RECOVERY_IMAGE"
    - bash -x ./build_twrp.sh "$DEVICE_TREE" "$DEVICE_BRANCH" "$DEVICE_CODENAME" "$MANIFEST_BRANCH" "$TARGET_RECOVERY_IMAGE"
  artifacts:
    path: output/**/*
  timeout_in: 120m
